### ISSUE TITLE
Скобочные массивы

### ISSUE THREAD

**Issue by tsukanov-as** [tsukanov-as/OneShell#11]
- [ ] ParenExpr должно содержать не одно выражение, а список.
- [ ] Убрать разбор массивов (пропуск запятых). Разбирать всегда как список выражений.

Присваивание массива будет выполняться так:
`x = (1, 2, 3)`
Передача массива параметром так:
`foo(x, y, (1, 2, 3))`
Параллельное присваивание из PowerShell типа:
`x, y = 1, 2, 3`
когда в `y` должен попасть хвост массива, следует писать так:
`x, y = 1, (2, 3)`

**Comment by dmpas** [comment]
как будет трактоваться
```bsl
x = (1) ;
```
??

**Comment by tsukanov-as** [comment]
Да, ты прав. Надо думать

**Comment by tsukanov-as** [comment]
Оставлю мысль на завтра:
`x = (1)` допустим будет аналогом `x = 1`
а вот `x = (,1)` - это уже присваивание массива из одного элемента.
Ну т.е. просто проверять ведущую запятую. Но при этом все же убрать повершельный пропуск запятых. Я даже не совсем понимаю семантику этого.
Например, `$x = ,,1` - это аналог `x = 1`
но `$x = ,,,,,,1` - это уже массив из одного элемента O_o

**Comment by tsukanov-as** [comment]
В пекло эти скобки и запятые. Одна морока.
Лучше сделать нормальные литералы массивов в квадратных скобках
