### ISSUE TITLE
Функции высшего порядка

### ISSUE THREAD

**Issue by tsukanov-as** [tsukanov-as/OneShell#13]
- [x] Расширить синтаксис, чтобы было возможно присваивание функции переменной.
- [x] Транслировать в PowerShell как scriptblock с замыканием

При парсинге выражения проверять первый токен:
1. Если "Function", то разбирать сигнатуру и тело функции
2. Иначе обычный разбор выражения

```bsl
Function Foo(x, Func)
    Return Func(x)
EndFunction

// присваивание переменной
hof = Function(x)
    Return x * 2
EndFunction

x = 2;
y = Foo(x, hof);

//передача параметром непосредственно
y = Foo(x, Function(x) Return x * 2 EndFunction);
```

**Comment by dmpas** [comment]
Очередная грабля в подарок:
```bsl
Function Foo()
  Return 1;
EndFunction

Foo = Function() Return 2; EndFunction

x = Foo(); // ???
```
с точки зрения синтаксиса 1С можно объявить переменную и функцию с одинаковым именем.

**Comment by tsukanov-as** [comment]
Спасибо )
Само по себе это вроде не проблема. Просто нужны правила игры. Например, сначала ищем функцию, потом переменную.
Но ты мне напомнил, что у меня скоп неразделенный...

**Comment by tsukanov-as** [comment]
Жук в скопе: #15

**Comment by tsukanov-as** [comment]
@dmpas Пораскинул я мозгами... Все же мне не очень нравится моя идея.
Допустим есть у нас код:
```bsl
...
foo = function(x) return x*2 endfunction
y = foo(2)
...
```
Сначала ищем функцию, потом переменную. Функции нет. Все работает.
Но допустим кода у нас много. И в процессе эволюции кто-то добавил в код функцию foo().
Хорошо если оно исключением бахнет. А если нет? Дебаг станет кошмаром.

По сему мне кажется, что вызов ВФП нужно выделять. Мне придумалось так:
```bsl
...
foo = function(x) return x*2 endfunction
y = @foo(2)
...
```
И символ в тему. И визуально выделяется.

**Comment by dmpas** [comment]
Символ не в тему. Очередной символ, ради которого надо раскладку переключать. В духе 1С должно быть что-нибудь вроде
```bsl
Фу = Функция (х) Возврат х*2; КонецФункции;
Жу = Вызвать Фу(2);
```

**Comment by tsukanov-as** [comment]
Ну я на русском не пишу и если честно даже уже и не понимаю зачем на нем писать. Русскую прикладуху удобнее, да. Но скрипты...

Грабли в твоем варианте: "Вызвать" - это новое ключевое слово. У меня и так уже `case when endcase` ломают совместимость.

**Comment by tsukanov-as** [comment]
Еще вариант:
```bsl
Фу = Функция (х) Возврат х*2; КонецФункции;
Жу = Фу.Вызвать(2);
```
Типа ФВП - это объект с одним методом

**Comment by tsukanov-as** [comment]
Вроде придумал годный вариант:
```bsl
Фу = Функция (х) Возврат х*2; КонецФункции;
Жу = Вызвать(Фу, 2);
```
