### ISSUE TITLE
Неверно восстанавливается текст запроса

### ISSUE THREAD

**Issue by akabrr** [tsukanov-as/OneShell#48]
На входе: 

> Запрос = Новый Запрос("
> 	|ВЫБРАТЬ ПЕРВЫЕ 1
> 	|	1 КАК Результат
> 	|ИЗ
> 	|	РегистрСведений.СкидкиНоменклатурыНатуральные.СрезПоследних(&Дата,
> 	|	   ПолучательСкидки В (&МассивПолучателей)) КАК СкидкиНатуральные
> 	|ЛЕВОЕ СОЕДИНЕНИЕ
> 	|	РегистрСведений.ВремяДействияСкидок КАК ВремяДействия
> 	|ПО
> 	|	СкидкиНатуральные.Регистратор = ВремяДействия.Регистратор
> 	|ГДЕ
> 	|	СкидкиНатуральные.СпецПредложение = &Номенклатура
> 	|	И СкидкиНатуральные.ХарактеристикаСпецПредложения = &ХарактеристикаНоменклатуры
> 	|	И (ВремяДействия.Регистратор ЕСТЬ NULL
> 	|	ИЛИ ВремяДействия.ДеньНедели = &ДеньНедели
> 	|	И (&ТекущееВремя МЕЖДУ ВремяДействия.ВремяНачала И ВремяДействия.ВремяОкончания)
> 	|	И (СкидкиНатуральные.ДатаОкончания = ДАТАВРЕМЯ(1, 1, 1)
> 	|	ИЛИ СкидкиНатуральные.ДатаОкончания >= &Дата))
> 	|");

На выходе, после BSL_VisitModule:

> Запрос = New Запрос("" "ВЫБРАТЬ ПЕРВЫЕ 1" "	1 КАК Результат" "ИЗ" "	РегистрСведений.СкидкиНоменклатурыНатуральные.СрезПоследних(&Дата," "	   ПолучательСкидки В (&МассивПолучателей)) КАК СкидкиНатуральные" "ЛЕВОЕ СОЕДИНЕНИЕ" "	РегистрСведений.ВремяДействияСкидок КАК ВремяДействия" "ПО" "	СкидкиНатуральные.Регистратор = ВремяДействия.Регистратор" "ГДЕ" "	СкидкиНатуральные.СпецПредложение = &Номенклатура" "	И СкидкиНатуральные.ХарактеристикаСпецПредложения = &ХарактеристикаНоменклатуры" "	И (ВремяДействия.Регистратор ЕСТЬ NULL" "	ИЛИ ВремяДействия.ДеньНедели = &ДеньНедели" "	И (&ТекущееВремя МЕЖДУ ВремяДействия.ВремяНачала И ВремяДействия.ВремяОкончания)" "	И (СкидкиНатуральные.ДатаОкончания = ДАТАВРЕМЯ(1, 1, 1)" "	ИЛИ СкидкиНатуральные.ДатаОкончания >= &Дата))" "");

Добавляются лишние символы "

**Comment by tsukanov-as** [comment]
Спасибо, за фидбэк!

Просьба уточнить где именно добавляются. На первый взгляд все правильно.

**Comment by tsukanov-as** [comment]
Тут возможно путает то, что весь текст в одну строку собирается.
Если вставить переносы вместо пробелов между строками, то станет понятнее:
```Запрос = New Запрос(  
""  
"ВЫБРАТЬ ПЕРВЫЕ 1"  
"	1 КАК Результат"  
"ИЗ"  
" РегистрСведений.СкидкиНоменклатурыНатуральные.СрезПоследних(&Дата,"  
"	ПолучательСкидки В (&МассивПолучателей)) КАК СкидкиНатуральные"  
"ЛЕВОЕ СОЕДИНЕНИЕ"  
" РегистрСведений.ВремяДействияСкидок КАК ВремяДействия"  
"ПО"  
" СкидкиНатуральные.Регистратор = ВремяДействия.Регистратор"  
"ГДЕ"  
" СкидкиНатуральные.СпецПредложение = &Номенклатура"  
"	И СкидкиНатуральные.ХарактеристикаСпецПредложения = &ХарактеристикаНоменклатуры"  
"	И (ВремяДействия.Регистратор ЕСТЬ NULL"  
"	ИЛИ ВремяДействия.ДеньНедели = &ДеньНедели"  
"	И (&ТекущееВремя МЕЖДУ ВремяДействия.ВремяНачала И ВремяДействия.ВремяОкончания)"   
"	И (СкидкиНатуральные.ДатаОкончания = ДАТАВРЕМЯ(1, 1, 1)"  
"	ИЛИ СкидкиНатуральные.ДатаОкончания >= &Дата))"  
""  
);```

**Comment by akabrr** [comment]
Согласен, не хватает переносов строк.

**Comment by tsukanov-as** [comment]
Я рад, что вы проявили интерес к этой разработке.
Обратите, пожалуйста, внимание на форк: https://github.com/Lead-Bullet/BSL-Parser
Там планируется полноценный парсер встроенного языка 1С. В AST планируется сохранять информацию о директивах, инструкциях препроцессора, комментариях и дополнительной информации об оформлении текста.

**Comment by akabrr** [comment]
Спасибо вам, гляну обязательно.
